// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "KNR Solutions",
            "email": "kethakaranasinghe@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/drugs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the list of drug catalogs with pagination, sorting, and filtering options",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrugCatalogs Actions"
                ],
                "summary": "List drug catalogs with pagination",
                "operationId": "drug-catalogs-list-paginated",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (e.g., created_at, updated_at)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of drug catalogs",
                        "schema": {
                            "$ref": "#/definitions/responses.DrugCatalogPaginationResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create drugcatalog",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrugCatalogs Actions"
                ],
                "summary": "Create drugcatalog",
                "operationId": "drugcatalogs-create",
                "parameters": [
                    {
                        "description": "DrugCatalog name and age",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateDrugCatalogRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/drugs/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a single drug catalog by its unique identifier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrugCatalogs Actions"
                ],
                "summary": "Get drug catalog by ID",
                "operationId": "drug-catalogs-get-by-id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "DrugCatalog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.DrugCatalogResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update drugcatalog",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrugCatalogs Actions"
                ],
                "summary": "Update drugcatalog",
                "operationId": "drugcatalogs-update",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "DrugCatalog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "DrugCatalog name and age",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateDrugCatalogRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete drugcatalog",
                "tags": [
                    "DrugCatalogs Actions"
                ],
                "summary": "Delete drugcatalog",
                "operationId": "drugcatalogs-delete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "DrugCatalog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/google-oauth": {
            "post": {
                "description": "Perform user login using google provider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Actions"
                ],
                "summary": "Authenticate user using google provider",
                "operationId": "user-auth-google",
                "parameters": [
                    {
                        "description": "Google Token",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.OAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/labTestCatalogs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the list of all labtestcatalogs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LabTestCatalogs Actions"
                ],
                "summary": "Get labtestcatalogs",
                "operationId": "labtestcatalogs-get",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/responses.LabTestCatalogResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create labtestcatalog",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LabTestCatalogs Actions"
                ],
                "summary": "Create labtestcatalog",
                "operationId": "labtestcatalogs-create",
                "parameters": [
                    {
                        "description": "LabTestCatalog name and age",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateLabTestCatalogRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/labTestCatalogs/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update labtestcatalog",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LabTestCatalogs Actions"
                ],
                "summary": "Update labtestcatalog",
                "operationId": "labtestcatalogs-update",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "LabTestCatalog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "LabTestCatalog name and age",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateLabTestCatalogRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete labtestcatalog",
                "tags": [
                    "LabTestCatalogs Actions"
                ],
                "summary": "Delete labtestcatalog",
                "operationId": "labtestcatalogs-delete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "LabTestCatalog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Perform user login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Actions"
                ],
                "summary": "Authenticate a user",
                "operationId": "user-login",
                "parameters": [
                    {
                        "description": "User's credentials",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/patients": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the list of patients with pagination, sorting, and filtering options",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patients Actions"
                ],
                "summary": "List patients with pagination",
                "operationId": "patients-list-paginated",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (e.g., created_at, updated_at)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of patients",
                        "schema": {
                            "$ref": "#/definitions/responses.PatientPaginationResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create patient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patients Actions"
                ],
                "summary": "Create patient",
                "operationId": "patients-create",
                "parameters": [
                    {
                        "description": "Patient name and age",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreatePatientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/patients/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update patient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patients Actions"
                ],
                "summary": "Update patient",
                "operationId": "patients-update",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Patient name and age",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdatePatientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete patient",
                "tags": [
                    "Patients Actions"
                ],
                "summary": "Delete patient",
                "operationId": "patients-delete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/posts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the list of all posts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts Actions"
                ],
                "summary": "Get posts",
                "operationId": "posts-get",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/responses.PostResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts Actions"
                ],
                "summary": "Create post",
                "operationId": "posts-create",
                "parameters": [
                    {
                        "description": "Post title and content",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/posts/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts Actions"
                ],
                "summary": "Update post",
                "operationId": "posts-update",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Post title and content",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete post",
                "tags": [
                    "Posts Actions"
                ],
                "summary": "Delete post",
                "operationId": "posts-delete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "description": "Perform refresh access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Actions"
                ],
                "summary": "Refresh access token",
                "operationId": "user-refresh",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "New user registration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Actions"
                ],
                "summary": "Register",
                "operationId": "user-register",
                "parameters": [
                    {
                        "description": "User's email, user's password",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/visits": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the list of visits with pagination, sorting, and filtering options",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visits Actions"
                ],
                "summary": "List visits with pagination",
                "operationId": "visits-list-paginated",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (e.g., created_at, updated_at)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of visits",
                        "schema": {
                            "$ref": "#/definitions/responses.VisitPaginationResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create visit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visits Actions"
                ],
                "summary": "Create visit",
                "operationId": "visits-create",
                "parameters": [
                    {
                        "description": "Visit title and content",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateVisitRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/responses.Data"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/visits/preview": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Preview a visit's prompt details by classifying using AI",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visits Actions"
                ],
                "summary": "Classify visit prompt",
                "operationId": "visits-preview",
                "parameters": [
                    {
                        "description": "Visit title and content",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.PreviewVisitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.VisitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        },
        "/visits/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a single visit by its unique identifier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visits Actions"
                ],
                "summary": "Get visit by ID",
                "operationId": "visits-get-by-id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Visit ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.VisitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AIResponse": {
            "type": "object",
            "properties": {
                "drugs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Drug"
                    }
                },
                "lab_tests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "notes": {
                    "type": "string"
                }
            }
        },
        "domain.Drug": {
            "type": "object",
            "properties": {
                "dosage": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "frequency": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "requests.CreateDrugCatalogRequest": {
            "type": "object",
            "required": [
                "default_price",
                "name"
            ],
            "properties": {
                "default_price": {
                    "type": "number",
                    "example": 1200
                },
                "name": {
                    "type": "string",
                    "example": "Dupixent"
                }
            }
        },
        "requests.CreateLabTestCatalogRequest": {
            "type": "object",
            "required": [
                "default_price",
                "name"
            ],
            "properties": {
                "default_price": {
                    "type": "number",
                    "example": 7500
                },
                "name": {
                    "type": "string",
                    "example": "Blood Test"
                }
            }
        },
        "requests.CreatePatientRequest": {
            "type": "object",
            "required": [
                "age",
                "gender",
                "name"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 34
                },
                "gender": {
                    "type": "string",
                    "example": "Male"
                },
                "name": {
                    "type": "string",
                    "example": "Saman Perera"
                }
            }
        },
        "requests.CreatePostRequest": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Echo is nice!"
                },
                "title": {
                    "type": "string",
                    "example": "Echo"
                }
            }
        },
        "requests.CreateVisitRequest": {
            "type": "object",
            "required": [
                "ai_result",
                "patient_id",
                "raw_input"
            ],
            "properties": {
                "ai_result": {
                    "$ref": "#/definitions/domain.AIResponse"
                },
                "patient_id": {
                    "type": "integer",
                    "example": 1
                },
                "raw_input": {
                    "type": "string",
                    "example": "Patient has fever for 3 days. Prescribe Paracetamol 500mg twice daily. Order CBC test."
                }
            }
        },
        "requests.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "11111111"
                }
            }
        },
        "requests.OAuthRequest": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "requests.PreviewVisitRequest": {
            "type": "object",
            "required": [
                "raw_input"
            ],
            "properties": {
                "raw_input": {
                    "type": "string",
                    "example": "Patient has fever for 3 days. Prescribe Paracetamol 500mg twice daily. Order CBC test."
                }
            }
        },
        "requests.RefreshRequest": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "type": "string",
                    "example": "refresh_token"
                }
            }
        },
        "requests.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "example": "11111111"
                }
            }
        },
        "requests.UpdateDrugCatalogRequest": {
            "type": "object",
            "required": [
                "default_price",
                "name"
            ],
            "properties": {
                "default_price": {
                    "type": "number",
                    "example": 1200
                },
                "name": {
                    "type": "string",
                    "example": "Dupixent"
                }
            }
        },
        "requests.UpdateLabTestCatalogRequest": {
            "type": "object",
            "required": [
                "default_price",
                "name"
            ],
            "properties": {
                "default_price": {
                    "type": "number",
                    "example": 7500
                },
                "name": {
                    "type": "string",
                    "example": "Blood Test"
                }
            }
        },
        "requests.UpdatePatientRequest": {
            "type": "object",
            "required": [
                "age",
                "gender",
                "name"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 34
                },
                "gender": {
                    "type": "string",
                    "example": "Male"
                },
                "name": {
                    "type": "string",
                    "example": "Saman Perera"
                }
            }
        },
        "requests.UpdatePostRequest": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Echo is nice!"
                },
                "title": {
                    "type": "string",
                    "example": "Echo"
                }
            }
        },
        "responses.ClinicalNoteResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "note": {
                    "type": "string",
                    "example": "some notes"
                },
                "visit_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "responses.Data": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.DrugCatalogPaginationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.DrugCatalogResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "sort": {
                    "type": "string",
                    "example": "1"
                },
                "total_pages": {
                    "type": "integer",
                    "example": 2
                },
                "total_rows": {
                    "type": "integer",
                    "example": 8
                }
            }
        },
        "responses.DrugCatalogResponse": {
            "type": "object",
            "properties": {
                "default_price": {
                    "type": "number",
                    "example": 1200
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Dupixent"
                }
            }
        },
        "responses.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "responses.LabTestCatalogResponse": {
            "type": "object",
            "properties": {
                "default_price": {
                    "type": "number",
                    "example": 7500
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Blood Test"
                }
            }
        },
        "responses.LabTestResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "price": {
                    "type": "number",
                    "example": 7500
                },
                "test_name": {
                    "type": "string",
                    "example": "ECG"
                },
                "visit_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "responses.LoginResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "exp": {
                    "type": "integer"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "refreshToken": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "responses.PatientPaginationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.PatientResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "sort": {
                    "type": "string",
                    "example": "1"
                },
                "total_pages": {
                    "type": "integer",
                    "example": 2
                },
                "total_rows": {
                    "type": "integer",
                    "example": 8
                }
            }
        },
        "responses.PatientResponse": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 34
                },
                "gender": {
                    "type": "string",
                    "example": "Male"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "Saman Perera"
                }
            }
        },
        "responses.PostResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Echo is nice!"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "Echo"
                },
                "username": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "responses.PrescribedDrugResponse": {
            "type": "object",
            "properties": {
                "dosage": {
                    "type": "string",
                    "example": "7500"
                },
                "drug_name": {
                    "type": "string",
                    "example": "ECG"
                },
                "duration": {
                    "type": "string",
                    "example": "5 days"
                },
                "frequency": {
                    "type": "string",
                    "example": "Once a day"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "price": {
                    "type": "number",
                    "example": 7500
                },
                "visit_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "responses.VisitPaginationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.VisitResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "sort": {
                    "type": "string",
                    "example": "1"
                },
                "total_pages": {
                    "type": "integer",
                    "example": 2
                },
                "total_rows": {
                    "type": "integer",
                    "example": 8
                }
            }
        },
        "responses.VisitResponse": {
            "type": "object",
            "properties": {
                "clinical_notes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.ClinicalNoteResponse"
                    }
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "lab_tests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.LabTestResponse"
                    }
                },
                "patient": {
                    "$ref": "#/definitions/responses.PatientResponse"
                },
                "patient_id": {
                    "type": "integer",
                    "example": 1
                },
                "prescribed_drugs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.PrescribedDrugResponse"
                    }
                },
                "raw_input": {
                    "type": "string",
                    "example": "Echo"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ABC Clinic",
	Description:      "This is a demo version of Echo app.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
